# See https://github.com/cypress-io/circleci-orb
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome99-ff88'
workflows:
  build:
    jobs:
      - cypress/run:
          config: 'pageLoadTimeout=100000,watchForFileChanges=false'        
          executor: with-chrome
          browser: chrome
          

     
