# See https://github.com/cypress-io/circleci-orb
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run

      # another independent job
      # testing how the orb can install and build
      # in the subfolder
     